services:
  mongodb:
    image: mongo:7
    container_name: baazarify-mongo
    restart: unless-stopped
    ports:
      - '27117:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: baazarify

  redis:
    image: redis:7-alpine
    container_name: baazarify-redis
    restart: unless-stopped
    ports:
      - '6479:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  mongodb_data:
  redis_data:
